#!/bin/bash

# Simple OpenVPN DNS update script

# Exit if we don't have the required variables
[ "$script_type" ] || exit 0
[ "$dev" ] || exit 0

RESOLV_CONF="/etc/resolv.conf"

# Main function
case "$script_type" in
  up)
    # Backup original resolv.conf
    if [ ! -f /etc/resolv.conf.backup ]; then
      cp /etc/resolv.conf /etc/resolv.conf.backup
    fi

    # Get DNS servers from OpenVPN
    dns_servers=""
    for opt in "$foreign_option_1" "$foreign_option_2" "$foreign_option_3" "$foreign_option_4"; do
      if [[ "$opt" =~ "dhcp-option DNS" ]]; then
        dns_ip=$(echo "$opt" | sed 's/dhcp-option DNS //')
        dns_servers="${dns_servers}nameserver $dns_ip\n"
      fi
    done

    # Update resolv.conf with VPN DNS servers
    if [ -n "$dns_servers" ]; then
      # Write the new resolv.conf
      echo -e "# Generated by OpenVPN\n${dns_servers}" > ${RESOLV_CONF}
    fi
    # After processing the VPN's DNS server, add additional ones
    echo "# Additional DNS servers for redundancy" >> ${RESOLV_CONF}
    echo "nameserver 1.1.1.1" >> ${RESOLV_CONF}  # Cloudflare
    echo "nameserver 9.9.9.9" >> ${RESOLV_CONF}  # Quad9
    ;;

  down)
    # Restore original resolv.conf
    if [ -f /etc/resolv.conf.backup ]; then
      cp /etc/resolv.conf.backup /etc/resolv.conf
    fi
    ;;
esac

exit 0
